defaultProject: jit-training-dma
defaultLocation: EU
defaultDataset: dataform
defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.42
vars:
    destination_dataset: dataset_academy_esercizio_AnnaOrlandi

